### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by tirli** [pomahtuk/sequilize-highlight#2]
Please, bump version and publish it to npm. Current master is supporting Winston and others, though npm version not :(

**Comment by scriptcoded** [comment]
Bump

**Comment by scriptcoded** [comment]
It has been over half a year. This is a really neat little package, so hey, keep it alive! @pomahtuk

**Comment by pomahtuk** [comment]
@scriptcoded @tirli Sorry for delay guys! As i am not using this in my personal workflow anymore, forgot about package. I've just published current master to npm.

Please tell me if it works fine.

**Comment by scriptcoded** [comment]
@pomahtuk Wonderful!

I would like to make this package a little more "noticable". I'm rewriting the readme, and structuring the code a little. Would you like me to continuously submit pull requests, or should I create a fork, and thereof a new repo?

**Comment by scriptcoded** [comment]
@pomahtuk Will you close this issue?
